### ISSUE TITLE
New bug in v1.4.0-1, path.lua:501: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by rushikeshz97** [Kong/lua-resty-aws#110]
/usr/local/share/lua/5.1/pl/path.lua:501: attempt to concatenate a nil value
stack traceback:
	/usr/local/share/lua/5.1/pl/path.lua:501: in function 'expanduser'
	/usr/local/share/lua/5.1/resty/aws/config.lua:240: in function 'load_config'
	/usr/local/share/lua/5.1/resty/aws/config.lua:289: in function 'get_config'
	/usr/local/share/lua/5.1/resty/aws/config.lua:350: in function '__index'

Hi this is a new issue we have encountered in your recent update 1.4.0. Seems to be caused by the change at **resty/aws/config.lua:240**, where you call **pl_path.expanduser(env_vars.AWS_CONFIG_FILE.value)**. 

Regards
Rushikesh

**Comment by Tieske** [comment]
@rushikeshz97 on what platform are you experiencing this? Looks to me that issue could only occur on Windows?

Have you tried setting up Nginx  such that the `HOME` environment variable does not get cleared? (when Nginx forks its worker processes, by default it will clear the env vars for security reasons)

**Comment by windmgc** [comment]
@Tieske We'll need this before the feature freeze of 3.7 of Kong gateway which should be 2 weeks later.

**Comment by Tieske** [comment]
Penlight release PR; https://github.com/lunarmodules/Penlight/pull/472
