### ISSUE TITLE
Can you give an proper example for any service method

### ISSUE THREAD

**Issue by aravindakumarbootlabs** [Kong/lua-resty-aws#27]

**Comment by Tieske** [comment]
see https://github.com/Kong/lua-resty-aws#example

**Comment by aravindakumarbootlabs** [comment]
the javascript sdk documentation shows most of the functions have two arguments, one is the inputRequest and the second is a callback, but this example that you have shared doesn't indicate how to set these two arguments, if possible can you kindly share a proper example with a real function.

**Comment by aravindakumarbootlabs** [comment]
@Tieske I have added an example and raised a PR, let me know if this is okay. #30

**Comment by Tieske** [comment]
I create #31 instead. Please have a look.
