### ISSUE TITLE
Incorrect URI generated for s3:PutObject

### ISSUE THREAD

**Issue by StarlightIbuki** [Kong/lua-resty-aws#33]
`{KEY+}` is not replaced.

The problem probably comes from:
https://github.com/Kong/lua-resty-aws/blob/bd1d16ba53fc88bbddbab9e1556295abe68ee5bf/src/resty/aws/request/build.lua#L103

Ref:
https://github.com/aws/aws-sdk-js/blob/c14da5afad7fa81c6889d2663743204b694f657c/dist/aws-sdk-react-native.js#L3717
The file is too large, so here is the line:
```js
		      var regex = new RegExp('\\{' + member.name + '(\\+)?\\}');
```

**Comment by StarlightIbuki** [comment]
Also, I noticed that the API definition file is out of sync with https://github.com/aws/aws-sdk-js

**Comment by Tieske** [comment]
the large file is an amalgamation of the whole library. This is the source line I think: 
https://github.com/aws/aws-sdk-js/blob/307e82673b48577fce4389e4ce03f95064e8fe0d/lib/protocol/rest.js#L17

**Comment by Tieske** [comment]
> Also, I noticed that the API definition file is out of sync with [aws/aws-sdk-js](https://github.com/aws/aws-sdk-js) (mostly, the difference is in documentation)

Since we have little tests around this library, I tend to not change unless broken. But maybe we should update indeed... wdyt?

**Comment by Tieske** [comment]
I guess these are the ones we're trying to fix:
https://github.com/aws/aws-sdk-js/blob/master/apis/s3-2006-03-01.normal.json#L106
