### ISSUE TITLE
Dependency on deprecated Penlight XML (pl.xml) module

### ISSUE THREAD

**Issue by flrgh** [Kong/lua-resty-aws#37]
[This module](https://github.com/Kong/lua-resty-aws/blob/2dd0ec19aa9e64df72b2380ed3433e9a764054a4/src/resty/aws/credentials/TokenFileWebIdentityCredentials.lua#L5) brings in `pl.xml` in order to parse an XML response from an STS call.

Since it's only this one code path, I wonder if we can just drop the XML parse operation instead of trying to find another suitable XML library. It's been so long since I've played with any of the AWS APIs directly though, and it's a tough one to google for--any idea if the STS API is capable of returning a json response?

**Comment by Tieske** [comment]
I doubt STS is the only XML one. Have you checked the SDK metadata for XML based ones?

Penlight XML is end-of-life though, so maybe we should replace it with proper XML, eg. LuaExpat?

**Comment by flrgh** [comment]
> I doubt STS is the only XML one.

I was actually very surprised to find this one credential handler was the _only_ user of `pl.xml` within ./src. There is some code in `resty.aws.request.build` that serializes a request to XML, but it does not use any dependencies to do so. There is a lot of magic/code-gen happening in here though, so there could be something else that's just not very `git grep`-able.

**Comment by StarlightIbuki** [comment]
Could we simply extract it with regex or even Lua string-matching function?

**Comment by windmgc** [comment]
>any idea if the STS API is capable of returning a json response?

Actually, it could, like this:
https://github.com/aws/aws-sdk-go/blob/d9ed7d6c12b09f718a2283c59a631fa91765e58e/aws/credentials/endpointcreds/provider.go#L166

We need to specify the `Accept` Header when sending requests

**Comment by Tieske** [comment]
Did a check on the `resty.aws.raw-api` folder, and there seem to be plenty of files there referencing xml. So just updating the `sts` to include an accept header is probably not enough.

From Kong 3.1, we'll have luaexpat available. So maybe wait for the release and then switch to that.

**Comment by Tieske** [comment]
should we start revisiting this?
