### ISSUE TITLE
Can i use `prepare_awsv4_request` in nginx?

### ISSUE THREAD

**Issue by donghyeon-kim98** [Kong/lua-resty-aws#5]
I want to use `prepare_awsv4_request` func in Nginx configuration like this library(https://github.com/jobteaser/lua-resty-aws-signature < It does not work 😢 )
How to build config and request_data?

**Comment by Tieske** [comment]
why not use the SDK?

Another implementation can be found in the Kong AWS lambda plugin, if you want to copy paste something, see https://github.com/Kong/kong-plugin-aws-lambda/blob/master/kong/plugins/aws-lambda/v4.lua

**Comment by donghyeon-kim98** [comment]
Thank you for your sharing 👍

**Comment by donghyeon-kim98** [comment]
I solve my problem
