### ISSUE TITLE
openresty use ssm service Increased memory

### ISSUE THREAD

**Issue by yuguangye** [Kong/lua-resty-aws#78]
openretsy: 1.21.4.1

When we use kong to initialize the ssm service object and call the getparameters interface, the more parameters, the greater the memory consumption. code is as follows:

> local ssm_kong -- Define global SSM variable
> 
> local function init_ssm_by_kong()
>     if ssm_kong then
>         logger:error("Reusing the existing AWS SSM")
>         return ssm_kong
>     end
>     logger:error("Initializing AWS SSM")
>     local AWS_global_config = resty_aws_config.global
>     local config_aws = { region = AWS_global_config.region }
>     local aws_result, aws = pcall(resty_aws, config_aws)
>     if not aws_result then
>         logger:error("Failed to initialize AWS: %s", aws)
>         return aws, nil
>     end
>     local ssm_result, new_ssm = pcall(aws.SSM, aws, { region = AWS_global_config.region })
>     if not ssm_result then
>         logger:error("Failed to initialize AWS SSM: %s", new_ssm)
>         return new_ssm, nil
>     end
>     ssm_kong = new_ssm -- Save the newly initialized SSM to global variable
>     logger:error("Successfully initialized AWS SSM")
>     return ssm_kong
> end
> 
> local function get_ssm_parameters_by_kong(names, with_decryption)
>     local local_ssm = init_ssm_by_kong()
>     local response, err = local_ssm:getParameters{
>         Names = names,
>         WithDecryption = with_decryption,
>     }
>     return {
>         response = response,
>         err = err,
>     }
> end

but the original aws-sdk method will not affect the memory. code is as follows:

> local function get_ssm_parameters(region, endpoint, names, with_decryption)
>     -- protect ENVs with older IMGs
>     if not LOADED_LIBS["aws-sdk.ssm"] then
>         logger:error("Failed to load aws-sdk.ssm, reason %s", sdk_conf)
>         return
>     end
>     sdk_ssm.init{ region = region, endpoint_override = endpoint }
>     local request = sdk_ssm.GetParametersRequest{
>         Names = names,
>         WithDecryption = with_decryption,
>     }
>     local _response, _error_type, _error_message
>     sdk_ssm.GetParametersAsync(request, function (response, error_type, error_message)
>         logger:debug ("%s", {response, error_type, error_message})
>         _response = response
>         _error_type = error_type
>         _error_message = error_message
>     end)
>     return {
>         response = _response,
>         error_type = _error_type,
>         error_message = _error_message,
>     }
> end

<img width="780" alt="image" src="https://github.com/Kong/lua-resty-aws/assets/130330966/2b393a43-ea6c-4ab5-9212-326ce8d86790">

 I don’t know why. Can you help me?

**Comment by yuguangye** [comment]
@Tieske @windmgc pls, thx a lot

**Comment by windmgc** [comment]
```
local ssm_result, new_ssm = pcall(aws.SSM, aws, { region = AWS_global_config.region })
if not ssm_result then
logger:error("Failed to initialize AWS SSM: %s", new_ssm)
return new_ssm, nil
end
ssm_kong = new_ssm -- Save the newly initialized SSM to global variable
logger:error("Successfully initialized AWS SSM")
return ssm_kong
```

It seems like every time your `get_ssm_parameters_by_kong` function is called, a new SSM service instance will be generated. This could result in many dangling objects in the LuaJIT runtime.

The correct way should be like the second example you provided, the service instance can be reused across every API call and does not need a second instantiation
