### ISSUE TITLE
Dynamodb get item nil

### ISSUE THREAD

**Issue by dblooman** [Kong/lua-resty-aws#89]
Im trying to fetch from dynamodb, but data keeps coming back as nil.

```lua
locat host = "example.com"
local result, err = dynamoClient:getItem({
    Key = {
        id = {
            S = host
        }
    },
    TableName = "tablename"
})
ngx.log(ngx.ERR, "err: ", err)
ngx.log(ngx.ERR, "result response: ", result.Item)
```

Its hard to debug as there is no error, but there is no data returned, so perhaps in the input is incorrect?

Im not familiar with this version of the dynamodb API, or lua, here is how i tested the data was present in Go

```go
package main

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

func main() {
	ctx := context.Background()
	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		panic(err)
	}

	svc := dynamodb.NewFromConfig(cfg)

	resp, err := svc.GetItem(ctx, &dynamodb.GetItemInput{
		Key: map[string]types.AttributeValue{
			"id": &types.AttributeValueMemberS{
				Value: "example.com",
			},
		},
		TableName: aws.String("tablename"),
	})

	if err != nil {
		panic(err)
	}

	fmt.Println(resp.Item["some_field"].(*types.AttributeValueMemberS).Value)
}
```
Is there somewhere i can look at debug logs from the API request to dynamo so i can see if the input is wrong?

**Comment by windmgc** [comment]
> ngx.log(ngx.ERR, "result response: ", result.Item)

The [result](https://github.com/Kong/lua-resty-aws/blob/120c6ce3443f010a9f19766b7b7ec2ed9d457ad5/src/resty/aws/request/execute.lua#L6-L11) should be a table which looks like
```
{ status, headers, reason, body }
```
You can check if `result.body.Item` has the correct return value, or if status is not 200 and failed because of some `reason`
