### ISSUE TITLE
luarocks install lua-resty-aws failed on Mac OS

### ISSUE THREAD

**Issue by AllenFang** [Kong/lua-resty-aws#91]
hello guys, I'm trying to install this package in my Mac OS(M2) but encountered an issue:

```
luaexpat 1.5.1-1 depends on lua >= 5.1 (5.4-1 provided by VM)
env MACOSX_DEPLOYMENT_TARGET=11.0 gcc -O2 -fPIC -I/opt/homebrew/opt/lua/include/lua5.4 -c src/lxplib.c -o src/lxplib.o -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -Isrc/
src/lxplib.c:12:10: fatal error: 'expat_config.h' file not found
#include "expat_config.h"
         ^~~~~~~~~~~~~~~~
1 error generated.

Error: Failed installing dependency: https://luarocks.org/luaexpat-1.5.1-1.src.rock - Build error: Failed compiling object src/lxplib.o
```

it is probably a known issue from luaexpat ?! -> https://github.com/lunarmodules/luaexpat/issues/32
but seems not solution yet.

Can someone help on this ? thank you 🙇

**Comment by windmgc** [comment]
Do you already have `expat` installed on your Mac?

**Comment by windmgc** [comment]
If you already have `expat` installed but still encounter this error, I think follow this comment https://github.com/lunarmodules/luaexpat/issues/32#issuecomment-1307009351 is the best solution

**Comment by AllenFang** [comment]
thanks for reminding @windmgc , it work when I manually install `expat` via homebrew and assign the `EXPAT_DIR` properly.

Let me issue a PR to update the readme 🙇  thank you

**Comment by Tieske** [comment]
see https://github.com/lunarmodules/luaexpat/pull/33

This is a problem with the expat installation on Mac, that header is required to be available, since settings in it will have an effect on the ABI of the compiled lib.

**Comment by AllenFang** [comment]
@Tieske  Seems the [PR](https://github.com/lunarmodules/luaexpat/pull/33) is still pending, can I say you PR can fix this problem permanently?
