### ISSUE TITLE
localhost endpoint doesn't work for AWS:SQS

### ISSUE THREAD

**Issue by AllenFang** [Kong/lua-resty-aws#93]
I'm trying to connect to SQS in local development by [localstack](https://docs.localstack.cloud/overview/), so I successfully setup a local SQS and it can send/receive message by command but it got some problem when I connect to SQS via `lua-resty-aws`

```lua
local instance = aws:SQS({
  apiVersion="2012-11-05",
  accessKeyId="test",
  secretAccessKey="test",
  region="eu-central-1",
  endpoint="http://localhost:4566"
})

local results, err = instance:getQueueUrl({
    QueueName = "test-queue"
})

print(results) // got nil
print(err) // got SQS:getQueueUrl() failed to connect to 'http://localhost:4566:80': no resolver defined to resolve "localhost:4566"
 ```
 
 Look above error message, somehow `lua-resty-aws` can't resolve `endpoint` properly? Above similar code is work well in Javascript version:
 
 ```js
const SQS = require('aws-sdk/clients/sqs');
const sqs = new SQS({
    apiVersion: "2012-11-05",
    accessKeyId: "test",
    secretAccessKey: "test",
    region: "eu-central-1",
    endpoint: "http://localhost:4566"
});

sqs.getQueueUrl({
    QueueName: "test-queue"
}, (error, data) => {
    if (error) {
      console.error(error.message);
    }

    const queueUrl = data['QueueUrl'];
    console.log(queueUrl)
  });
```

> Notes: because `lua-resty-aws` is built by v2.751.0, I also downgrade my JS SDK version to v2.751.0 and it still work to connect the local SQS

Did I did something wrong? or is there any better way to custom the endpoint? Seems this lib doesn't support the `AWS.Endpoint` service which isn't like JS version, so I can't find any other ways to solve it. 

thanks  🙇

**Comment by windmgc** [comment]
Try separate port from endpoint, like https://github.com/Kong/lua-resty-aws/blob/120c6ce3443f010a9f19766b7b7ec2ed9d457ad5/spec/04-services/02-s3.lua#L41-L45

**Comment by AllenFang** [comment]
thanks @windmgc , it work acutally.
